ALTER TABLE subscriptions 
ADD COLUMN product_id VARCHAR(50) DEFAULT NULL,
ADD COLUMN variant_id VARCHAR(50) DEFAULT NULL,
ADD COLUMN product_name VARCHAR(255) DEFAULT NULL,
ADD COLUMN variant_name VARCHAR(255) DEFAULT NULL,
ADD COLUMN renews_at DATETIME DEFAULT NULL,
ADD COLUMN ends_at DATETIME DEFAULT NULL,
ADD COLUMN card_brand VARCHAR(50) DEFAULT NULL,
ADD COLUMN card_last_four VARCHAR(4) DEFAULT NULL,
ADD COLUMN update_payment_method_url TEXT DEFAULT NULL,
ADD COLUMN customer_portal_url TEXT DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `payments` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `subscription_id` INT DEFAULT NULL,
    `lemonsqueezy_order_id` VARCHAR(100) NOT NULL UNIQUE,
    `order_number` VARCHAR(50) DEFAULT NULL,
    `amount` DECIMAL(10, 2) NOT NULL,
    `currency` VARCHAR(10) DEFAULT 'USD',
    `status` VARCHAR(50) DEFAULT 'paid',
    `receipt_url` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
